import { Suspense } from 'react'
import Header from './components/header'

import './globals.css'
import Loader from './components/loader/loader'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen">
        <Header />
        {/* <div
          variants={ cursorVariants }
          animate={ cursorBG }
          className='w-[32px] h-[32px] bg-primary fixed top-0 left-0 pointer-events-none
        z-50 rounded-full'></div> */}
          <Suspense fallback={ <Loader/> }>
            {children}
          </Suspense>
      </body>
    </html>
  )
}
