import Header from './components/header'

import './globals.css'

export const metadata = {
  title: 'ikb Multimedia',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
