
import './globals.css';
import Script from 'next/script'
export const metadata = {
  title: 'ikb Multimedia',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="it">
        <body>
      {children}
        </body>
        <Script id="dangerouslySetInnerHTML" dangerouslySetInnerHTML={{ __html: `
            var _iub = _iub || [];
            _iub.csConfiguration = {
              "askConsentAtCookiePolicyUpdate":true,
              "enableLgpd":true,
              "floatingPreferencesButtonDisplay":"bottom-right",
              "perPurposeConsent":true,
              "siteId":3672185,
              "whitelabel":false,
              "cookiePolicyId":50123761,
              "lang":"it",
              "banner":{
                "acceptButtonCaptionColor":"#FFFFFF",
                "acceptButtonColor":"#0073CE",
                "acceptButtonDisplay":true,
                "backgroundColor":"#FFFFFF",
                "closeButtonRejects":true,
                "customizeButtonCaptionColor":"#4D4D4D",
                "customizeButtonColor":"#DADADA",
                "customizeButtonDisplay":true,
                "explicitWithdrawal":true,
                "listPurposes":true,
                "position":"float-top-center",
                "showTitle":false,
                "textColor":"#000000"
              }
            };
          `}} />
          <Script id="iubenta1" src="https://cs.iubenda.com/autoblocking/3672185.js" type="text/javascript"></Script>
          <Script id="iubenta2" src="//cdn.iubenda.com/cs/iubenda_cs.js" type="text/javascript" charset="UTF-8" async></Script>
    </html>
  );
}
